apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: neo4j
  template:
    metadata:
      labels:
        app: neo4j
    spec:
      containers:
        - name: neo4j
          image: neo4j:4.2.3
          ports:
            - containerPort: 7474
            - containerPort: 7687
          env:
            - name: NEO4J_AUTH
              value: "neo4j/some_password"

---
apiVersion: v1
kind: Service
metadata:
  name: neo4j
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 7474
    - name: bolt
      port: 7687
  selector:
    app: neo4j
